# Generated by Django 5.0.6 on 2024-06-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AI', 'AI'), ('Human', 'Human')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf_admin.coversation')),
            ],
        ),
    ]
