# Generated by Django 5.0.6 on 2024-06-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversation',
            name='chain',
            field=models.FileField(upload_to=''),
        ),
    ]
