"""
Django settings for pdf_analyser project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-_tr=+8=6c(f0ayxssk-#ai35#zuy083+d#j_nwj+_5sns1&e5g'


# SECURITY WARNING: don't run with debug turned on in production!
debug =  int(config('debug'))

ALLOWED_HOSTS = ["ec2-18-221-156-209.us-east-2.compute.amazonaws.com","127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'pdf_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',
      'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pdf_analyser.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pdf_analyser.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

SECRET_KEY = 'django-insecure-_tr=+8=6c(f0ayxssk-#ai35#zuy083+d#j_nwj+_5sns1&e5g'

if debug == 1:
    SECRET_KEY = 'django-insecure-_tr=+8=6c(f0ayxssk-#ai35#zuy083+d#j_nwj+_5sns1&e5g'
    DEBUG = True
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "OPTIONS": {
                "service": "pdf_db",
                "passfile": ".my_pgpass",
            },
        }
    }
    
else:
    #SECRET_KEY = os.environ.get("SECRET_KEY")
    DEBUG = False
    # db_from_env = dj_database_url.config(conn_max_age=600)
    # DATABASES = {'default':db_from_env}
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'pdf_db',
        'USER': 'admin',
        'PASSWORD': config("db_pass"),
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


if debug == 1:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # media directory in the root directory
    MEDIA_URL = '/media/'
else: 
    MEDIA_ROOT = os.path.join(BASE_DIR, 'mediadata') # media directory in the root directory
    MEDIA_URL = '/mediadata/'
